name: Build & Release


on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  build-version-number: 0.1.${{ github.run_number }}
  package-version-number: 0.1.${{ github.run_number }}

jobs:
  sca:
    name: SCA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
          
      - name: dotnet tool restore
        run: dotnet tool restore
              
      - name: Run SCA
        run: dotnet pkgchk --transitive true --deprecated
      
  check-style:
    name: Check code style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
                
      - name: Restore tools
        run: dotnet tool restore

      - name: Check style
        run: dotnet format --verify-no-changes

  codeql:
    uses: ./.github/workflows/codeql-analysis.yml
    
  package:
    name: Build package and release
    runs-on: ubuntu-latest
    needs: [ check-style, sca, codeql ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
                
      - name: Restore tools
        run: dotnet tool restore
              
      - name: Restore solutiom
        run: dotnet restore

      - name: Set package version
        if: github.ref != 'refs/heads/main' 
        run: |
          echo "package-version-number=${{ env.package-version-number }}-preview" >> $GITHUB_ENV

      - name: Package
        run: dotnet pack -c Release -o ./package/ -p:PackageVersion=${{ env.package-version-number }}

      - name: Push package to Nuget
        if: github.event_name == 'push'
        run: dotnet nuget push "artifacts/*.nupkg"  --api-key ${{ secrets.NUGET_PAT }} --source "nuget.org"

  gh-release:
    name: Github release
    runs-on: ubuntu-latest
    needs: [ package ]    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:    
      - uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.build-version-number }}
          prerelease: false
          generateReleaseNotes: true